spring:
  profiles:
    active: local
    include:
      - db
      - oauth
      - jwt
      - sentry

  jpa:
    hibernate:
      ddl-auto: none
    show_sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
        dialect: org.hibernate.dialect.MySQLDialect

logging:
  level:
    org.hibernate.type: trace                   # ???? ??? ????? ? ? ?? ?? ??
    org.hibernate.type.descriptor.sql: trace    # sql? ? ?? Parameter? ???.